### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by ghost** [Vins2106/urlcord#1]
I am having a few issues with the login. 

![Screen Shot 2021-02-09 at 11 40 42 AM](https://user-images.githubusercontent.com/72352701/107418612-b7d49600-6acb-11eb-90de-2a8a94ee34b1.png)

So I get this even though I have (mysiteurl)/login as a oauth2 redirect url. So then I make a link myself, then click on it
![Screen Shot 2021-02-09 at 11 44 31 AM](https://user-images.githubusercontent.com/72352701/107419055-3598a180-6acc-11eb-88f1-8d058d6c5881.png)

How do I fix this?

**Comment by Vins2106** [comment]
> I am having a few issues with the login.
> 
> ![Screen Shot 2021-02-09 at 11 40 42 AM](https://user-images.githubusercontent.com/72352701/107418612-b7d49600-6acb-11eb-90de-2a8a94ee34b1.png)
> 
> So I get this even though I have (mysiteurl)/login as a oauth2 redirect url. So then I make a link myself, then click on it
> ![Screen Shot 2021-02-09 at 11 44 31 AM](https://user-images.githubusercontent.com/72352701/107419055-3598a180-6acc-11eb-88f1-8d058d6c5881.png)
> 
> How do I fix this?

hello, im sorry for the late reply
first, you go to https://discord.com/developers/applications

and choose your bot,
and then go to Oauth2 page and add redirects url, the redirect url is https://locahost:3000/callback or https://yourwebsite.com/callback

have have the screenshoot example
![image](https://user-images.githubusercontent.com/69247128/110235609-b04fb380-7ef6-11eb-8c78-7c2f0d6a5900.png)

**Comment by ghost** [comment]
> > I am having a few issues with the login.
> > ![Screen Shot 2021-02-09 at 11 40 42 AM](https://user-images.githubusercontent.com/72352701/107418612-b7d49600-6acb-11eb-90de-2a8a94ee34b1.png)
> > So I get this even though I have (mysiteurl)/login as a oauth2 redirect url. So then I make a link myself, then click on it
> > ![Screen Shot 2021-02-09 at 11 44 31 AM](https://user-images.githubusercontent.com/72352701/107419055-3598a180-6acc-11eb-88f1-8d058d6c5881.png)
> > How do I fix this?
> 
> hello, im sorry for the late reply
> first, you go to https://discord.com/developers/applications
> 
> and choose your bot,
> and then go to Oauth2 page and add redirects url, the redirect url is https://locahost:3000/callback or https://yourwebsite.com/callback
> 
> have have the screenshoot example
> ![image](https://user-images.githubusercontent.com/69247128/110235609-b04fb380-7ef6-11eb-8c78-7c2f0d6a5900.png)

Thank you! I appreciate the reply. Now when I go on the dashboard and press manage it is stuck endlessly loading and not taking me onto the page. 
![image](https://user-images.githubusercontent.com/72352701/110988186-18eac600-8325-11eb-887e-828f807cce4a.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/72352701/110989169-57cd4b80-8326-11eb-82f6-fd17beebf07b.png)
This is the error that comes up every time I press manage.

The code line it jumps to:
![image](https://user-images.githubusercontent.com/72352701/110989412-b5619800-8326-11eb-92b2-10e28ebe4ea4.png)

**Comment by Vins2106** [comment]
> ![image](https://user-images.githubusercontent.com/72352701/110989169-57cd4b80-8326-11eb-82f6-fd17beebf07b.png)
> This is the error that comes up every time I press manage.
> 
> The code line it jumps to:
> ![image](https://user-images.githubusercontent.com/72352701/110989412-b5619800-8326-11eb-92b2-10e28ebe4ea4.png)

Hello again!
please enable your bot members presence intents in discord developers 

screenshot :
![image](https://cdn.discordapp.com/attachments/820027319930191952/820156397441646612/unknown.png)

**Comment by ghost** [comment]
Thank you! :)
